# Generated by Django 4.1.7 on 2023-03-03 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diriginti', '0003_alter_diriginte_aol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Santier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tip_santier', models.CharField(choices=[('Bransament', 'bransament'), ('Extindere', 'extindere'), ('Deviere', 'deviere'), ('Sistematizare', 'sistematizare'), ('Reabilitare', 'reabilitare'), ('Redimensionare', 'redimensionare')], max_length=25)),
                ('localitate', models.CharField(max_length=25)),
                ('strada', models.CharField(max_length=40)),
                ('numar', models.CharField(max_length=10, null=True)),
                ('tip_lucrari', models.CharField(max_length=25)),
                ('constructor', models.CharField(max_length=40)),
                ('SDA', models.CharField(max_length=13)),
                ('numar_aparitie', models.IntegerField()),
                ('status', models.CharField(choices=[('Amanat', 'amanat'), ('In lucru', 'in lucru'), ('Executat', 'executat'), ('Sistat', 'sistat')], max_length=10, null=True)),
                ('observatie', models.CharField(max_length=100)),
                ('nota', models.IntegerField()),
                ('poza1', models.ImageField(null=True, upload_to='img/')),
                ('poza2', models.ImageField(null=True, upload_to='img/')),
                ('poza3', models.ImageField(null=True, upload_to='img/')),
                ('document', models.FileField(null=True, upload_to='file/')),
                ('diriginte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diriginti.diriginte')),
            ],
        ),
    ]
