# Generated by Django 4.1.7 on 2023-03-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santiere', '0002_alter_santier_nota_alter_santier_numar_aparitie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='santier',
            name='solicitare',
            field=models.FileField(null=True, upload_to='file'),
        ),
        migrations.AlterField(
            model_name='santier',
            name='observatie',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
