# Generated by Django 4.1.7 on 2023-03-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santiere', '0003_santier_solicitare_alter_santier_observatie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santier',
            name='status',
            field=models.CharField(choices=[('amanat', 'amanat'), ('in lucru', 'in lucru'), ('executat', 'executat'), ('sistat', 'sistat')], max_length=10, null=True),
        ),
    ]
