# Generated by Django 4.1.7 on 2023-03-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santiere', '0004_alter_santier_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='santier',
            name='are_poza',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='santier',
            name='are_vizita',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='santier',
            name='vizita',
            field=models.FileField(null=True, upload_to='file/vizite/'),
        ),
        migrations.AlterField(
            model_name='santier',
            name='document',
            field=models.FileField(null=True, upload_to='file/alte_doc/'),
        ),
        migrations.AlterField(
            model_name='santier',
            name='solicitare',
            field=models.FileField(null=True, upload_to='file/solicitari/'),
        ),
    ]
