# Generated by Django 4.1.7 on 2023-03-30 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diriginti', '0003_alter_diriginte_aol'),
        ('santiere', '0005_santier_are_poza_santier_are_vizita_santier_vizita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santier',
            name='are_poza',
            field=models.CharField(default='Nu', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='santier',
            name='are_vizita',
            field=models.CharField(default='Nu', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='santier',
            name='diriginte',
            field=models.ForeignKey(default='x', null=True, on_delete=django.db.models.deletion.CASCADE, to='diriginti.diriginte'),
        ),
    ]
