# Generated by Django 4.1.7 on 2023-03-30 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diriginti', '0003_alter_diriginte_aol'),
        ('santiere', '0006_alter_santier_are_poza_alter_santier_are_vizita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santier',
            name='diriginte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diriginti.diriginte'),
        ),
    ]
