# Generated by Django 4.1.7 on 2023-03-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santiere', '0007_alter_santier_diriginte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santier',
            name='status',
            field=models.CharField(choices=[('amanat', 'amanat'), ('in lucru', 'in lucru'), ('executat', 'executat'), ('sistat', 'sistat'), (' ', '--')], default='--', max_length=10),
        ),
    ]
