# Generated by Django 4.1.7 on 2023-02-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diriginte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('prenume', models.CharField(max_length=50)),
                ('AOL', models.CharField(max_length=20)),
                ('marca', models.IntegerField(verbose_name=6)),
                ('activ', models.BooleanField(default=True)),
            ],
        ),
    ]
