# Generated by Django 4.1.7 on 2023-02-28 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diriginti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diriginte',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diriginte',
            name='email',
            field=models.EmailField(default=0, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diriginte',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='diriginte',
            name='AOL',
            field=models.CharField(choices=[('Bv', 'AOL Brasov'), ('Buc', 'AOL Bucuresti'), ('Bz', 'AOL Buzau'), ('Ct', 'AOL Constanta'), ('Cr', 'AOL Craiova'), ('Gl', 'AOL Galati'), ('Pt', 'AOL Pitesti'), ('Pl', 'AOL Ploiesti')], max_length=15),
        ),
        migrations.AlterField(
            model_name='diriginte',
            name='marca',
            field=models.IntegerField(),
        ),
    ]
