# Generated by Django 4.1.7 on 2023-03-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diriginti', '0002_diriginte_created_at_diriginte_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diriginte',
            name='AOL',
            field=models.CharField(choices=[('AOL Brasov', 'AOL Brasov'), ('AOL Bucuresti', 'AOL Bucuresti'), ('AOL Buzau', 'AOL Buzau'), ('AOL Constanta', 'AOL Constanta'), ('AOL Craiova', 'AOL Craiova'), ('AOL Galati', 'AOL Galati'), ('AOL Pitesti', 'AOL Pitesti'), ('AOL Ploiesti', 'AOL Ploiesti')], max_length=15),
        ),
    ]
